version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: hydra-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: hydra
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - hydra_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  hydra_data:
